apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Nginx Ingress Controller Baremetal Deployment
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/baremetal/deploy.yaml
  
  # Custom Resources
  - cert-manager-issuer.yaml
  - custom-error-backend.yaml
  - ingress.yaml

# Patching Nginx Controller for basic prometheus monitoring
patches:
  - target:
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ingress-nginx-controller
        namespace: ingress-nginx
      spec:
        template:
          metadata:
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "10254"
