apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuroscan-deployment
  labels:
    app: neuroscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuroscan
  template:
    metadata:
      labels:
        app: neuroscan

    spec:
      serviceAccountName: neuroscan-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: neuroscan
        image: aniketpuro/neuroscan:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        env:
        - name: PORT
          value: "5001"
        - name: SECRET_KEY
          value: "production-secret-key-change-me"
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: db-volume
          mountPath: /app/instance
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: db-volume
        hostPath:
          path: /opt/neuroscan/instance
          type: DirectoryOrCreate
