apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuroscan-deployment
  labels:
    app: neuroscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuroscan
  template:
    metadata:
      labels:
        app: neuroscan

    spec:
      serviceAccountName: neuroscan-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: neuroscan
        image: aniketpuro/neuroscan:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5001
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5001
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: PORT
          value: "5001"
        - name: TF_CPP_MIN_LOG_LEVEL
          value: "2"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: neuroscan-secrets
              key: SECRET_KEY
        - name: MISTRAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: neuroscan-secrets
              key: MISTRAL_API_KEY
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: db-volume
          mountPath: /app/instance
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: db-volume
        hostPath:
          path: /opt/neuroscan/instance
          type: DirectoryOrCreate
