apiVersion: v1
kind: ServiceAccount
metadata:
  name: neuroscan-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neuroscan-role
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neuroscan-rolebinding
subjects:
- kind: ServiceAccount
  name: neuroscan-sa
  namespace: default
roleRef:
  kind: Role
  name: neuroscan-role
  apiGroup: rbac.authorization.k8s.io
